Fix unused variable and parameter warnings from gcc
Deals with the following warnings (errors in strict mode) by removing
the offending code and dropping a parameter name, respectively.

  src/pathfind/teleport.cpp: In member function ‘void pathfind::teleport_group::get_teleport_pair(pathfind::teleport_pair&, const unit&, bool) const’:
  src/pathfind/teleport.cpp:70:12: error: variable ‘units’ set but not used [-Werror=unused-but-set-variable]

  src/pathfind/teleport.cpp:66:16: error: unused parameter ‘ignore_units’ [-Werror=unused-parameter]

iceiceice, you probably should take a look at this.