Fix failure to build on current versions of MSVC
A recent change in an upstream library must've resulted in an indirect
inclusion of <chrono> disappearing:

  D:\wesnoth-1.18\src\log.cpp(429): error C2039: 'high_resolution_clock': is not a member of 'std::chrono'

Whatever the case may be, adding one of our own fixes this and poses no
issue on other platforms.

(Not needed in the dev branch since the same include was already added
by commit 2d765118ed48a976b102c5b296a8062d0846922a.)