temporarily revert 2011-05-03T20:18:53Z!koraq@xs4all.nl by mordante:
..."Fixed gcc 4.6 compiler warnings."

this commit caused 1.8 to not allow playing *at all* and thus testing
is impossible, sample error from starting Two Brothers:

20110507 12:04:43 error general: Error while playing the game:
                                 game_error: unknown unit type: Knight

please fix the issues and recommit a working version