SConstruct: Do not link with libintl - Wesnoth now uses boost::locale
http://forums.wesnoth.org/viewtopic.php?f=10&p=577648

This fixes compilation error on MinGW:
...
g++ -o wesnothd.exe -mwindows -mthreads build\release\sd... -lboost_locale-mgw49-mt-1_57 -lwsock32 -lintl -lz
../lib/gcc/i686-w64-mingw32/4.9.2/../../../../i686-w64-mingw32/bin/ld.exe: cannot find -lintl
collect2.exe: error: ld returned 1 exit status
scons: *** [wesnothd.exe] Error 1
scons: building terminated because of errors.