Fix strict compilation due to 2010-11-08T03:02:01Z!anonymissimus@arcor.de
Fixes the following compiler error:

src/scripting/lua.cpp:1565: error: suggest parentheses around ‘&&’ within ‘||’

I hope to have got the logic right here. Anonymissimus should confirm.