fix https://github.com/wesnoth/wesnoth/commit/8ba57c4290ae5f4788228c7561302da2b5008e48 break compilation with gcc called by codeblock projectfiles
i have this when i compile with gcc called via codeblock projectfile.
||=== Build file: Release in tests (compiler: GNU GCC Compiler) ===|
C:\D\Nouv. dossier\Nouv. dossier\wesnoth-master\src\tests\main.cpp||In constructor 'wesnoth_global_fixture::wesnoth_global_fixture()':|
C:\D\Nouv. dossier\Nouv. dossier\wesnoth-master\src\tests\main.cpp|78|error: no matching function for call to 'std::basic_ofstream<char>::open(const value_type*)'|
C:\mingw64\lib\gcc\x86_64-w64-mingw32\8.1.0\include\c++\fstream|851|note: candidate: 'void std::basic_ofstream<_CharT, _Traits>::open(const char*, std::ios_base::openmode) [with _CharT = char; _Traits = std::char_traits<char>; std::ios_base::openmode = std::_Ios_Openmode]'|
C:\mingw64\lib\gcc\x86_64-w64-mingw32\8.1.0\include\c++\fstream|851|note:   no known conversion for argument 1 from 'const value_type*' {aka 'const wchar_t*'} to 'const char*'|
C:\mingw64\lib\gcc\x86_64-w64-mingw32\8.1.0\include\c++\fstream|871|note: candidate: 'void std::basic_ofstream<_CharT, _Traits>::open(const string&, std::ios_base::openmode) [with _CharT = char; _Traits = std::char_traits<char>; std::__cxx11::string = std::__cxx11::basic_string<char>; std::ios_base::openmode = std::_Ios_Openmode]'|
C:\mingw64\lib\gcc\x86_64-w64-mingw32\8.1.0\include\c++\fstream|871|note:   no known conversion for argument 1 from 'const value_type*' {aka 'const wchar_t*'} to 'const string&' {aka 'const std::__cxx11::basic_string<char>&'}|
C:\mingw64\lib\gcc\x86_64-w64-mingw32\8.1.0\include\c++\fstream|892|note: candidate: 'template<class _Path> std::_If_fs_path<_Path, void> std::basic_ofstream<_CharT, _Traits>::open(const _Path&, std::ios_base::openmode) [with _Path = _Path; _CharT = char; _Traits = std::char_traits<char>]'|
C:\mingw64\lib\gcc\x86_64-w64-mingw32\8.1.0\include\c++\fstream|892|note:   template argument deduction/substitution failed:|
C:\D\Nouv. dossier\Nouv. dossier\wesnoth-master\src\tests\main.cpp|78|required from here|
C:\mingw64\lib\gcc\x86_64-w64-mingw32\8.1.0\include\c++\fstream|892|error: request for member 'make_preferred' in 'std::declval<const wchar_t*&>()', which is of non-class type 'const wchar_t*'|
||=== Build failed: 2 error(s), 1 warning(s) (0 minute(s), 12 second(s)) ===|

and i suse gcc-8.1.0 --threads=posix --exceptions=seh --arch=x86_64